### ISSUE TITLE
XMPP Domain hardcoded

### ISSUE THREAD

**Issue by LaSepp** [pascomnet/teleclient#1]
Im Konstruktor der XmppConnection (Connection.cs) ist die Domain "mobydick" hart verdrahtet.
Sobald die sys.xmpp.domain geändert ist klappt die Verbindung ohne sinnvolle Fehlermeldung nicht mehr.

Ladebalken läuft dann, es erscheint nur im /var/log/xmppd/info.log eine Meldung dass die Anmeldung verweigert wurde, der Client meldet nichts.

**Comment by lichtzeichner** [comment]
Hallo LaSepp, erstmal vielen Dank für deine Rückmeldung. Der "teleclient" ist nur eine sehr einfache Beispielapplikation, die anhand einer möglichst kleinen Codebasis die Verwendung der mobydick XMPP-API illustrieren soll. - Zuviele Optionen würden hier IMHO nur die Verständlichkeit reduzieren.

Wenn du das aber tatsächlich ändern möchtest, freuen wir uns jederzeit über einen Pull-Request!
